INFO:__main__:Initial date available in archive: 2015-11-28 00:00:00
INFO:__main__:Total number of leadtimes: 43152
INFO:__main__:Found a checkpoint at time :2016-01-03 05:00:00
INFO:__main__:Starting from hour :870
Traceback (most recent call last):
  File "/scratch-shared/meteoswiss/scratch/cosuna/cosmo-archive-retrieve/scripts/../cosmo_archive_retrieve/create_zarr_archive.py", line 472, in <module>
    load_data(data_config)
  File "/scratch-shared/meteoswiss/scratch/cosuna/cosmo-archive-retrieve/scripts/../cosmo_archive_retrieve/create_zarr_archive.py", line 292, in load_data
    with tempfile.TemporaryDirectory(prefix=config["tempdir"]) as tmpdir:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/cosuna/miniconda3/envs/cosmo-archive-retrieve/lib/python3.11/tempfile.py", line 871, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/cosuna/miniconda3/envs/cosmo-archive-retrieve/lib/python3.11/tempfile.py", line 385, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scratch/cosuna/1bf5m1m7'
